In [15]:
import numpy as np
import numpy.linalg as la
from func import *

In [16]:
from sympy import Poly
from sympy.polys import ring, QQ
RR, x = ring("x", QQ)

In [31]:
def vectorToToeplitz2(v,numCols):
    band_width = len(v)
    H = np.zeros((numCols+len(v)-1, numCols))
    for col in range(numCols):
        H[col:col+band_width , col] = v
    return H

def buildModuloMat2(modPoly,deg):
    poly = sym_allcoeffs(modPoly)
    polyDeg = len(poly)-1
    T = vectorToToeplitz2(poly,deg-polyDeg+1)
    K = T[:polyDeg,:]
    L = T[polyDeg:]
    E = np.hstack([np.eye(polyDeg), -np.dot(K,la.inv(L))])
    return E

# returns N,n coefficients
def getBerzetPolys2(M,m):
    cM = sym_allcoeffs(M)
    cm = sym_allcoeffs(m)
    dM = len(cM)-1
    dm = len(cm)-1
    TM = vectorToToeplitz2(cM,dm)
    Tm = vectorToToeplitz2(cm,dM)
    T = np.hstack([TM,Tm])
    coeffs = la.solve(T,np.append(1,np.zeros(dm+dM-1)))
    return [coeffs[:dm],coeffs[dm:]]

In [32]:
print(buildModuloMats2(x**2+x-4,4))

[[ 1.  0.  4. -4. 20.]
 [ 0.  1. -1.  5. -9.]]


In [33]:
poly = np.asarray([x+1,x+5,x**2-10+10*x-5])
P = 1
for p in poly:
    P *= p
print("Prod:",P)
    
i = 2
M = P/poly[i]
m = poly[i]
N,n = getBerzetPolys(M,m,RR,x)
# print(M)

print("M:",M)
print("m:",m)
print("N:",N)
print("n:",n)
print("===========")
print(M*N)
print(m*n)

Prod: x**4 + 16*x**3 + 50*x**2 - 40*x - 75
M: x**2 + 6*x + 5
m: x**2 + 10*x - 15
N: 1/240*x + 1/16
n: -1/240*x - 11/240
1/240*x**3 + 7/80*x**2 + 19/48*x + 5/16
-1/240*x**3 - 7/80*x**2 - 19/48*x + 11/16


In [34]:
cM = sym_allcoeffs(M)
cm = sym_allcoeffs(m)
cN = sym_allcoeffs(N)
cn = sym_allcoeffs(n)

TM = vectorToToeplitz2(cM,2)
Tm = vectorToToeplitz2(cm,2)

T = np.hstack([TM,Tm])
o = np.append(1,np.zeros(3))
print(T)
print(o)
coeffs = la.solve(T,o)
print(coeffs)

print(TM)
print(cN)
print(Tm)
print(cn)

[[  5.   0. -15.   0.]
 [  6.   5.  10. -15.]
 [  1.   6.   1.  10.]
 [  0.   1.   0.   1.]]
[1. 0. 0. 0.]
[ 0.0625      0.00416667 -0.04583333 -0.00416667]
[[5. 0.]
 [6. 5.]
 [1. 6.]
 [0. 1.]]
[0.0625     0.00416667]
[[-15.   0.]
 [ 10. -15.]
 [  1.  10.]
 [  0.   1.]]
[-0.04583333 -0.00416667]


In [35]:
poly = np.asarray([x**2-4,x**3+2,x,x-1])
P = 1
for p in poly:
    P *= p
print("Prod:",P)
    
i = 2
M = P/poly[i]
m = poly[i]
N,n = getBerzetPolys(M,m,RR,x)
# print(M)

print("M:",M)
print("m:",m)
print("N:",N)
print("n:",n)
print("===========")
print(M*N)
print(m*n)

Prod: x**7 - x**6 - 4*x**5 + 6*x**4 - 2*x**3 - 8*x**2 + 8*x
M: x**6 - x**5 - 4*x**4 + 6*x**3 - 2*x**2 - 8*x + 8
m: x
N: 1/8
n: -1/8*x**5 + 1/8*x**4 + 1/2*x**3 - 3/4*x**2 + 1/4*x + 1
1/8*x**6 - 1/8*x**5 - 1/2*x**4 + 3/4*x**3 - 1/4*x**2 - x + 1
-1/8*x**6 + 1/8*x**5 + 1/2*x**4 - 3/4*x**3 + 1/4*x**2 + x


In [53]:
poly = np.asarray([x-1,x+1,x**2+1,x**4+1])
P = 1
for p in poly:
    P *= p
print("Prod:",P)
    
i = 2
M = P/poly[i]
m = poly[i]
N,n = getBerzetPolys(M,m,RR,x)
# print(M)

print("M:",M)
print("m:",m)
print("N:",N)
print("n:",n)
print("===========")
print("===========")
print("Prod1:",M*N)
print("Prod2:",m*n)
cM = sym_allcoeffs(M)
print("cM:",cM)
print("cm:",cm)
cN = sym_allcoeffs(N)
TcM = vectorToToeplitz2(cM,len(cN))
prod1 = TcM @ cN
print("Prod1:",prod1)

print(solveBerzouts(M,m))

Prod: x**8 - 1
M: x**6 - x**4 + x**2 - 1
m: x**2 + 1
N: -1/4
n: 1/4*x**4 - 1/2*x**2 + 3/4
Prod1: -1/4*x**6 + 1/4*x**4 - 1/4*x**2 + 1/4
Prod2: 1/4*x**6 - 1/4*x**4 + 1/4*x**2 + 3/4
cM: [-1.  0.  1.  0. -1.  0.  1.]
cm: [1. 0. 0. 0. 1.]
Prod1: [ 0.25  0.   -0.25  0.    0.25  0.   -0.25]
[array([-0.25, -0.  ]), array([ 0.75,  0.  , -0.5 ,  0.  ,  0.25,  0.  ])]


In [28]:
# Mi = M/mi
# N,n = getBerzetPolys2(Mi,mi)
# E = buildIdeMat(N*Mi,M,mi)

In [118]:
poly = np.asarray([x-1,x+1,x**2+1,x**4+1])
P = 1
for p in poly:
    P *= p
print("Prod:",P)

i = 2
M = P/poly[i]
m = poly[i]
N,n = getBerzetPolys(M,m,RR,x)
# print(M)

print("M:",M)
print("m:",m)
print("N:",N)
print("n:",n)
print("===========")
print("Prod1:",M*N)
print("Prod2:",m*n)

print(solveBerzouts(M,m))

Prod: x**8 - 1
M: x**6 - x**4 + x**2 - 1
m: x**2 + 1
N: -1/4
n: 1/4*x**4 - 1/2*x**2 + 3/4
Prod1: -1/4*x**6 + 1/4*x**4 - 1/4*x**2 + 1/4
Prod2: 1/4*x**6 - 1/4*x**4 + 1/4*x**2 + 3/4
[array([-0.25, -0.  ]), array([ 0.75,  0.  , -0.5 ,  0.  ,  0.25,  0.  ])]


### Running Winograd with new Matrix Generators

In [148]:
def winoMats(polys):
    M = getProdPoly(polys)
    deg_M = sym_deg(M)
    
    AA = None
    CC = None
    EE = None
    first = True
    
    for mi in polys:
        deg_m = sym_deg(mi)
        
        # evaluate in modulo
        X = buildModuloMat2(mi,deg_M-1)
        C,A,_ = toomCookMats(deg_m,deg_m)
        A = np.dot(A,X)
        AA = (A if first else np.vstack([AA,A]))

        # evaluates interpolation modulo, recall we will have
        # two degree deg_m-1
        X = buildModuloMat2(mi,2*deg_m-2)
        C = np.dot(X,C)
        CC = (C if first else scila.block_diag(CC,C))

        # recovery by the CRT
        Mi = M/mi
        cMi = sym_allcoeffs(Mi)
        cmi = sym_allcoeffs(mi)
        cN,_ = getBerzetPolys2(Mi,mi)
        TcM = vectorToToeplitz2(cMi,len(cN))
        cE = np.dot(TcM,cN)
        E = vectorToToeplitz2(cE,deg_m)
        
        # evaluate modulo M
        X = buildModuloMat2(M,len(E)-1)
        E = np.dot(X,E)
        
        EE = (E if first else np.hstack([EE,E]))
        first = False
            
    EC = np.dot(EE,CC)
    return [EC,AA,AA]

In [149]:
poly = np.asarray([x+1,x-1,x**2+1,x**4+1])
[C,A,B] = winoMats(poly)

In [151]:
f = np.ones(8)
g = np.ones(8)

y = C @ ((np.dot(A,f) * np.dot(B,g)))
print(y)

[8. 8. 8. 8. 8. 8. 8. 8.]


### Winograd with different input sizes

Suppose we want to convolve a $4 \times 5$.

In [178]:
def winoMats(polys,r,n):
    M = getProdPoly(polys)
    deg_M = sym_deg(M)
    
    AA = None
    BB = None
    CC = None
    EE = None
    first = True
    
    for mi in polys:
        deg_m = sym_deg(mi)
        
        # evaluate in modulo
        C,A,B = toomCookMats(deg_m,deg_m)
        X = buildModuloMat2(mi,r-1)
        A = np.dot(A,X)
        AA = (A if first else np.vstack([AA,A]))
        X = buildModuloMat2(mi,n-1)
        B = np.dot(B,X)
        BB = (B if first else np.vstack([BB,B]))

        # evaluates interpolation modulo, recall we will have
        # two degree deg_m-1
        X = buildModuloMat2(mi,2*deg_m-2)
        C = np.dot(X,C)
        CC = (C if first else scila.block_diag(CC,C))

        # recovery by the CRT
        Mi = M/mi
        cMi = sym_allcoeffs(Mi)
        cmi = sym_allcoeffs(mi)
        cN,_ = getBerzetPolys2(Mi,mi)
        TcM = vectorToToeplitz2(cMi,len(cN))
        cE = np.dot(TcM,cN)
        E = vectorToToeplitz2(cE,deg_m)
        
        # evaluate modulo M
        X = buildModuloMat2(M,len(E)-1)
        E = np.dot(X,E)
        
        EE = (E if first else np.hstack([EE,E]))
        first = False
            
    EC = np.dot(EE,CC)
    return [EC,AA,BB]

In [187]:
r = 2
n = 5

poly = np.asarray([x,x-1,x+1,x-2])
[C,A,B] = winoMats(poly,r,n)
print(C)
print(A)
print(B)

f = np.ones(r)
g = np.ones(n)

y = C @ ((np.dot(A,f) * np.dot(B,g)))
print(y)

[[ 1.          0.          0.          0.        ]
 [-0.5         1.         -0.33333333 -0.16666667]
 [-1.          0.5         0.5         0.        ]
 [ 0.5        -0.5        -0.16666667  0.16666667]]
[[ 1.  0.]
 [ 1.  1.]
 [ 1. -1.]
 [ 1.  2.]]
[[ 1.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 1. -1.  1. -1.  1.]
 [ 1.  2.  4.  8. 16.]]
[ 1. -6.  4. 11.]
