In [1]:
import numpy as np
import numpy.linalg as la
from func import *

### Testing [Vincent's](https://openreview.net/pdf?id=H1ZaRZVKg) paper

We first see if we can achieve or get close to Vincent's results for $9 \times 9$ filters

In [4]:
p1 = np.asarray([0,1,-1,1/2,-1/2,1/3,-1/3,3/2,-3/12,-3,2,-2,1])
p2 = np.asarray([1,1,1,1,1,1,1,1,1,1,1,1,0])

print(len(p1),len(p2))

13 13


In [59]:
V1 = np.vander(p1,increasing=True)
V2 = np.vander(p2,increasing=False)
Vx = V1 * V2

V1 = np.vander(p1,increasing=True,N=9)
V2 = np.vander(p2,increasing=False,N=9)
Vy = V1 * V2

V1 = np.vander(p1,increasing=True,N=5)
V2 = np.vander(p2,increasing=False,N=5)
Vw = V1 * V2

cond1 = np.asarray([la.cond(Vy,p=2),la.cond(Vx,p=2),\
                    la.cond(Vw,p=2)])
print(cond1)

[7.87057002e+04 8.72283106e+08 6.11469865e+01]


In [48]:
sy = np.asarray([-4/3,1/20,0.1,-0.7314286,-1.024,\
               1.314635,1.643293,-0.005277263,\
               -0.01583179,-1.587302e-5,0.0003265306,
               0.001632653,1])
sx = np.asarray([-3/4,20,10,-1.367188,-0.9765625,0.7606677,\
                0.6085342,-189.4922,-63.16406,-63000,3062.5,\
                 612.5,1])

sw = np.ones(13)/(sy * sx)

SY = np.diag(sy)
SX = np.diag(sx)
SW = np.diag(sw)

In [62]:
VX = SX @ la.inv(Vx.T)
VY = Vy.T @ SY
VW = SW @ Vw

cond2 = np.asarray([la.cond(VY,p=2),la.cond(VX,p=2),\
                    la.cond(VW,p=2)])
print(cond2)

print("\nImprovements:",cond1/cond2)

[1.41337199e+02 8.21345233e+05 6.11469754e+01]

Improvements: [5.56864722e+02 1.06201762e+03 1.00000018e+00]


### Inverse Stuff

In [96]:
p = np.asarray([0,1,-1,2,-2,3,-3,4,-4])
V = np.vander(p,increasing=True)
V[-1,:] = 0; V[-1,-1] = 1
V2 = la.inv(V)
print(la.cond(V2,p=2))
print(la.svd(V)[1][-1])

print(V)
print(V2[:,-1])

17571231.137134526
0.0038866297560661085
[[    1     0     0     0     0     0     0     0     0]
 [    1     1     1     1     1     1     1     1     1]
 [    1    -1     1    -1     1    -1     1    -1     1]
 [    1     2     4     8    16    32    64   128   256]
 [    1    -2     4    -8    16   -32    64  -128   256]
 [    1     3     9    27    81   243   729  2187  6561]
 [    1    -3     9   -27    81  -243   729 -2187  6561]
 [    1     4    16    64   256  1024  4096 16384 65536]
 [    0     0     0     0     0     0     0     0     1]]
[   0.  144.  -36. -196.   49.   56.  -14.   -4.    1.]
