In [1]:
import numpy as np
import numpy.linalg as la

### Journal Overview

This entry seeks to look at Chebyshev transforms via DCT-I to verify the results from [cite](https://pdf.sciencedirectassets.com/271586/1-s2.0-S0024379500X00225/1-s2.0-0024379595006966/main.pdf?x-amz-security-token=AgoJb3JpZ2luX2VjEOf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJIMEYCIQCoxj8bvc6Jg2IoO5kAEnffbRe21zfIiI%2Bg6n3yYGl6WwIhALFnxVRh529YKYQSZDTtSRZp551Vnkd1D562K2rZAkidKtoDCC8QAhoMMDU5MDAzNTQ2ODY1Igwi8uSjT7%2Bez32l44sqtwMyhlHbGjmZs4%2BjjNlWLbCm2km97CPcHuqg8md%2FIrWMZfqf6PbWirapkI1ybIZHUkmDiaota%2B4MvNs2h2BNS90vIxrIXi5cerCl%2BLUkQg0uBlf7KSFLG1DkVQlKq0cLZiysmsS7pQvnvvFLXjU80lJk1E6BhqWMWnTpMx2mcyCxVyAQV3scMEuPrQBKgRbfcG8Wx%2Bfm9r%2BMHUGvpBdGVJFsnjWZJbVu6AbmR0B5KLdPMScBac3NHoa7tpYfzzejhj2%2BngXqXnBUeRmg8dpUiRub3SOJyad6Eak9TkYfbSs8jNJaTyJ0oQ%2FJ1bxAChKgg3GWB49pwsJ03z8fludCZBKaajG%2FmWl3gF0RvKcSLNDnRHdEWeNgZG%2BxSvGd2QeTNz5gtQyojlY54w%2FaY%2FJVPunw3FQrtTNzjHvyIkPEmGbYMxDXiFBcD60soyKxTVTlPftewEzUHUq6rU57tbb4phqqnLes0d%2BR%2BjMR6V1D8Dp6k7OFE%2B9y8CIpcQoRO3YX8jDZzqJVrwfuiMCwi7kXNajbj3L3lcyapCSjr3olm0FNC%2FVNyJXJBW7VX2YEDdGCSLuLUJoQMKOZMPD9zegFOrMBAWr0SkyK40KSAxkMr%2Fs2NkBLH6qm0WkSrH866BY9Tc%2BJ7%2ByqRromURjkv1ZHa%2F3Gi6rDtJyoNZbCIeuCT9Bv3TsX0CI51akSqQP%2Br30GbsK%2FgHVxF87KeRlkHj4QKQADesYqPNSSBlg4xg3wo%2FQ08Y2lrY7GQ4czz%2FQJRBWbS%2Fz2DGlx5mfKCxtzi1Lt316CAiO4EKWhivkhS5POuMJFmbYhFW8Oe1z85mLmnlGqKdZuIDc%3D&AWSAccessKeyId=ASIAQ3PHCVTYWTGQLZJU&Expires=1561563616&Signature=QAZ%2Fe9Af1pKIGZbfvIIUl02T%2FO0%3D&hash=d4ef1cdf40807d9583a2f5b15647c19ae6d8f50aaf6b2fb41515c9eda0ac4001&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=0024379595006966&tid=spdf-c384cf3e-080e-46ed-b83f-f697587a7cba&sid=7014c49540b8274377394d526068a30f2f5fgxrqa&type=client)

### DCT-I Algorithms

In [201]:
def transformVec(v):
    # returns 2n-2 size input
    return np.append(v,v[1:-1][::-1])

def DCT_mat(n):
    # computes DCT(n)
    M = np.zeros((n,n))
    for u in range(n):
        for k in range(n):
            e = (.5 if k==0 or k==n-1 else 1)
            M[u,k] = ( e * np.cos((u*k*np.pi)/(n-1)) )
    return M

def DCTI_2n(a,b):
    # DCT-(N+1)
    n = len(a)
    assert(n == len(b))

    DC = DCT_mat(2*n+1)

    az = np.append(a,np.zeros(n+1))
    bz = np.append(b,np.zeros(n+1))

    c = np.dot(DC,az) * np.dot(DC,bz)
    return (2/n) * np.dot(DC, c)

def DCTI_2nb(a,b):
    # DCT-(N+1)
    n = len(a)-1
    v = len(b)-1
    N = n+v+1

    DC = DCT_mat(N+1)

    az = np.append(a,np.zeros(N-n))
    bz = np.append(b,np.zeros(N-v))

    c = np.dot(DC,az) * np.dot(DC,bz)
    return (2/N) * np.dot(DC, c)

### Application of DCT to convolution

In [192]:
n = 150
a = np.random.random(n)
b = np.random.random(n)
c = DCTI_2n(a,b)

# circular convolution
az = np.append(a,np.zeros(n+1))
bz = np.append(b,np.zeros(n+1))
x = transformVec(az)
y = transformVec(bz)
z = np.real(np.fft.ifft( np.fft.fft(x) * np.fft.fft(y) ))
z = z[:2*n+1]

print("Error:",la.norm(c-z)/la.norm(z))

Error: 8.80749004807787e-16


### Application of DCT to Chebyshev Multiplication

In [193]:
n = 3
f = np.random.random(n)
g = np.random.random(n)

In [194]:
z = 2*n-1
i = np.arange(n, dtype=np.float64)
j = np.arange(z, dtype=np.float64)

# Chebyshev nodes:
t = nodes = np.cos((2*j+1)/(2*z)*np.pi)

# dim: (nodes, i)
V = np.cos(i * np.arccos(t.reshape(-1, 1)))
Vfull = np.cos(j * np.arccos(t.reshape(-1, 1)))

print("V trnc conditioning:",la.cond(V,p=2))
print("V full conditioning:",la.cond(Vfull,p=2))

print(Vfull.shape)

V trnc conditioning: 1.4142135623730951
V full conditioning: 1.414213562373096
(5, 5)


First, we use the Chebyshev matrix to perform the necessary multiplication

In [197]:
c1 = np.dot(la.inv(Vfull), np.dot(V,f) * np.dot(V,g))
print(c1)

[0.41878808 1.13034971 0.47595209 0.3632804  0.05616525]


Now we use the DCT transform of

$$c = \frac{2}{N}C_N^I\Big(C_N^If \odot C_N^Ig\Big)$$

In [200]:
c2 = DCTI_2nb(f,g)[:2*n-1]
print(c2)

5
[0.49798904 0.74681505 0.30609175 0.3632804  0.05616525]


In [205]:
C1 = DCT_mat(4)
C2 = DCT_mat(4)
print(1 * C1 @ C2)

[[ 1.50000000e+00  2.22044605e-16 -2.22044605e-16  0.00000000e+00]
 [ 1.11022302e-16  1.50000000e+00  1.11022302e-16  5.55111512e-17]
 [-1.11022302e-16  1.11022302e-16  1.50000000e+00 -3.33066907e-16]
 [ 0.00000000e+00  1.11022302e-16 -6.66133815e-16  1.50000000e+00]]
